name: Neo4j Migration with Vector Embeddings

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  migrate:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # 2 hour timeout for large migrations
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0  # Fetch full history for better git operations
      
    - name: Set up Pixi
      uses: prefix-dev/setup-pixi@v0.8.14
      with:
        pixi-version: latest
        
    - name: Install dependencies
      run: pixi install
      
    - name: Run Neo4j Migration with Vector Embeddings
      run: pixi run neo4j-migrate-with-vectors
      env:
        NEO4J_CONNECTION_URI: ${{ secrets.NEO4J_CONNECTION_URI }}
        NEO4J_USERNAME: ${{ secrets.NEO4J_USERNAME }}
        NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
        INCLUDE_VECTOR_EMBEDDINGS: "true"
        
    - name: Summary
      run: |
        echo "## Neo4j Migration Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Started**: $(date -u)" >> $GITHUB_STEP_SUMMARY
        echo "- **Migration**: Completed with vector embeddings" >> $GITHUB_STEP_SUMMARY
        echo "- **Embeddings**: Native Neo4j TF-IDF based (512 dimensions)" >> $GITHUB_STEP_SUMMARY
        echo "- **External APIs**: None (offline operation)" >> $GITHUB_STEP_SUMMARY