name: Scrape HazMap Registry

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # 1 hour timeout to prevent indefinite runs
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0  # Fetch full history for better git operations
      
    - name: Set up Pixi
      uses: prefix-dev/setup-pixi@v0.8.12
      with:
        pixi-version: latest
        
    - name: Install dependencies
      run: pixi install
      
    - name: Run scraper
      run: pixi run python src/scripts/scrape_registry.py
      
    - name: Check for new files
      id: check_files
      run: |
        if [ -n "$(git status --porcelain data/)" ]; then
          echo "files_changed=true" >> $GITHUB_OUTPUT
        else
          echo "files_changed=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Configure Git
      if: steps.check_files.outputs.files_changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Pull latest changes before commit
      if: steps.check_files.outputs.files_changed == 'true'
      run: |
        echo "Pulling latest changes to avoid conflicts..."
        git pull origin main --rebase || {
          echo "Rebase failed, trying merge strategy"
          git rebase --abort 2>/dev/null || true
          git pull origin main --no-rebase
        }
        
    - name: Check for conflicts after pull
      if: steps.check_files.outputs.files_changed == 'true'
      run: |
        if git status --porcelain | grep -q "^UU\|^AA\|^DD"; then
          echo "Merge conflicts detected, aborting"
          git status
          exit 1
        fi
        
    - name: Commit registry files
      if: steps.check_files.outputs.files_changed == 'true'
      run: |
        git add data/
        git commit -m "feat: update HazMap registry files - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        
    - name: Push changes with retry logic
      if: steps.check_files.outputs.files_changed == 'true'
      run: |
        # Retry push up to 3 times in case of conflicts
        for i in {1..3}; do
          echo "Push attempt $i/3..."
          
          # Pull latest changes before each push attempt
          git pull origin main --rebase || {
            echo "Rebase failed, trying merge"
            git rebase --abort 2>/dev/null || true
            git pull origin main --no-rebase
          }
          
          # Check for conflicts
          if git status --porcelain | grep -q "^UU\|^AA\|^DD"; then
            echo "Conflicts detected on attempt $i, resolving..."
            git status
            continue
          fi
          
          # Attempt push
          if git push origin main; then
            echo "✅ Successfully pushed on attempt $i"
            break
          else
            echo "❌ Push failed on attempt $i"
            if [ $i -eq 3 ]; then
              echo "Failed to push after 3 attempts"
              git status
              git log --oneline -5
              exit 1
            else
              echo "Retrying in 3 seconds..."
              sleep 3
            fi
          fi
        done
        
    - name: Summary
      run: |
        echo "## Scraping Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Started**: $(date -u)" >> $GITHUB_STEP_SUMMARY
        echo "- **Files changed**: ${{ steps.check_files.outputs.files_changed }}" >> $GITHUB_STEP_SUMMARY
        if [ -d "data/" ]; then
          echo "- **Registry files**:" >> $GITHUB_STEP_SUMMARY
          ls -la data/*_registry_*.yml | while read -r line; do
            echo "  - $line" >> $GITHUB_STEP_SUMMARY
          done
        fi
