name: Scrape HazMap Registry

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0  # Fetch full history for better git operations
      
    - name: Set up Pixi
      uses: prefix-dev/setup-pixi@v0.8.11
      with:
        pixi-version: latest
        
    - name: Install dependencies
      run: pixi install
      
    - name: Run scraper
      run: pixi run python src/scripts/scrape_registry.py
      
    - name: Check for new files
      id: check_files
      run: |
        if [ -n "$(git status --porcelain data/)" ]; then
          echo "files_changed=true" >> $GITHUB_OUTPUT
        else
          echo "files_changed=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Configure Git
      if: steps.check_files.outputs.files_changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Pull latest changes
      if: steps.check_files.outputs.files_changed == 'true'
      run: |
        git pull origin main --rebase || {
          echo "Rebase failed, trying merge strategy"
          git rebase --abort 2>/dev/null || true
          git pull origin main --no-rebase
        }
        
    - name: Commit registry files
      if: steps.check_files.outputs.files_changed == 'true'
      run: |
        git add data/
        git commit -m "🤖 Update HazMap registry files - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        
    - name: Push changes
      if: steps.check_files.outputs.files_changed == 'true'
      run: |
        # Retry push up to 3 times in case of conflicts
        for i in {1..3}; do
          if git push origin main; then
            echo "Successfully pushed on attempt $i"
            break
          else
            echo "Push failed on attempt $i, retrying..."
            if [ $i -lt 3 ]; then
              git pull origin main --rebase
              sleep 2
            else
              echo "Failed to push after 3 attempts"
              exit 1
            fi
          fi
        done
        
    - name: Summary
      run: |
        echo "## Scraping Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Started**: $(date -u)" >> $GITHUB_STEP_SUMMARY
        echo "- **Files changed**: ${{ steps.check_files.outputs.files_changed }}" >> $GITHUB_STEP_SUMMARY
        if [ -d "data/" ]; then
          echo "- **Registry files**:" >> $GITHUB_STEP_SUMMARY
          ls -la data/*_registry_*.yml | while read -r line; do
            echo "  - $line" >> $GITHUB_STEP_SUMMARY
          done
        fi
